import type { NewProduct } from "./schema";

const PX = (id: string, q: string) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800&w=800${q}`;

export const seedProducts: NewProduct[] = [
  {
    name: "Classic Tiramisu",
    slug: "classic-tiramisu",
    category: "tiramisu",
    shortDesc: "The original. Smooth, light, balanced coffee profile.",
    description:
      "A layered tiramisu with a smooth, light finish and a balanced coffee profile. Made with premium mascarpone, freshly brewed coffee and a delicate dusting of cocoa. Served in a 250 ml takeaway box.",
    price: 150,
    unit: "250 ml Takeaway Box",
    image: PX("10170054", ""),
    tags: "Bestseller,Eggless,Coffee",
    isBestseller: true,
    rating: 4.9,
    reviews: 212,
    sortOrder: 1,
  },
  {
    name: "Chocolate Tiramisu (Amul)",
    slug: "chocolate-tiramisu",
    category: "tiramisu",
    shortDesc: "Rich chocolate-forward tiramisu with deep choco ganache.",
    description:
      "A rich chocolate-forward tiramisu with creamy mascarpone layers and a deep Amul choco-ganache. For anyone who wants their coffee dessert with a serious chocolate hit. 250 ml.",
    price: 170,
    unit: "250 ml Takeaway Box",
    image: PX("7190368", ""),
    tags: "Eggless,Chocolate",
    isBestseller: true,
    rating: 4.8,
    reviews: 168,
    sortOrder: 2,
  },
  {
    name: "Ferrero Rocher Tiramisu",
    slug: "ferrero-rocher-tiramisu",
    category: "tiramisu",
    shortDesc: "Creamy mascarpone, espresso layers, crunchy Ferrero Rocher.",
    description:
      "A luxurious blend of creamy mascarpone, rich espresso-soaked layers and crunchy Ferrero Rocher pieces. Every spoonful delivers a perfect balance of chocolate and hazelnut. 250 ml.",
    price: 250,
    unit: "250 ml Takeaway Box",
    image: "/images/ferrero-tiramisu.jpg",
    tags: "Premium,Eggless,Hazelnut",
    isBestseller: true,
    rating: 5,
    reviews: 143,
    sortOrder: 3,
  },
  {
    name: "Nutella Tiramisu",
    slug: "nutella-tiramisu",
    category: "tiramisu",
    shortDesc: "Smooth Nutella, silky mascarpone, coffee-soaked layers.",
    description:
      "Made with smooth Nutella, silky mascarpone cream and delicate coffee-soaked layers. A rich, creamy dessert crafted for true chocolate lovers in every bite. 250 ml.",
    price: 250,
    unit: "250 ml Takeaway Box",
    image: "/images/nutella-tiramisu.jpg",
    tags: "Premium,Eggless,Nutella",
    rating: 4.9,
    reviews: 121,
    sortOrder: 4,
  },
  {
    name: "Dark Chocolate Tiramisu",
    slug: "dark-chocolate-tiramisu",
    category: "tiramisu",
    shortDesc: "Premium Amul dark chocolate, less sweet, intense.",
    description:
      "Crafted with premium Amul dark chocolate, creamy mascarpone and delicate coffee-soaked layers. Intense, less sweet and beautifully balanced. 250 ml.",
    price: 210,
    unit: "250 ml Takeaway Box",
    image: PX("8498186", ""),
    tags: "Eggless,Dark Chocolate",
    rating: 4.8,
    reviews: 96,
    sortOrder: 5,
  },
  {
    name: "Lotus Biscoff Tiramisu",
    slug: "lotus-biscoff-tiramisu",
    category: "tiramisu",
    shortDesc: "Caramelised Biscoff biscuits + creamy mascarpone.",
    description:
      "Layers of creamy mascarpone, coffee-soaked finger chips and crunchy Lotus Biscoff biscuits, finished with rich Biscoff spread. Caramel heaven. 250 ml.",
    price: 250,
    unit: "250 ml Takeaway Box",
    image: "/images/biscoff-tiramisu.jpg",
    tags: "Bestseller,Eggless,Biscoff",
    isBestseller: true,
    rating: 5,
    reviews: 187,
    sortOrder: 6,
  },
  {
    name: "Puddle Cake",
    slug: "puddle-cake",
    category: "cakes",
    shortDesc: "Ultra-moist chocolate cake with a rich chocolate glaze.",
    description:
      "An ultra-moist chocolate cake topped with a rich chocolate glaze. Every spoonful is soft, gooey and filled with deep chocolate indulgence. 250 ml.",
    price: 150,
    unit: "250 ml Takeaway Box",
    image: "/images/puddle-cake.jpg",
    tags: "Eggless,Chocolate",
    rating: 4.9,
    reviews: 134,
    sortOrder: 7,
  },
  {
    name: "Rasmalai Tres Leches",
    slug: "rasmalai-tres-leches",
    category: "cakes",
    shortDesc: "Soft sponge soaked in rasmalai milk with saffron cream.",
    description:
      "Soft sponge soaked in rasmalai milk, layered with rich saffron-infused cream and topped with authentic rasmalai, pistachios and almonds. An Indian-fusion favourite. 250 ml.",
    price: 200,
    unit: "250 ml Takeaway Box",
    image: "/images/rasmalai-tres-leches.jpg",
    tags: "Bestseller,Eggless,Fusion",
    isBestseller: true,
    rating: 4.9,
    reviews: 158,
    sortOrder: 8,
  },
  {
    name: "Eggless Fudgy Brownies",
    slug: "eggless-fudgy-brownies",
    category: "brownies",
    shortDesc:
      "Classic, Walnut, Nutella, Biscoff, Ferrero, Dark Amul & Cashew.",
    description:
      "Rich, fudgy and freshly baked to perfection. Available in a variety of flavours: Classic Chocolate, Walnut Brownie, Nutella Brownie, Lotus Biscoff Brownie, Ferrero Rocher Brownie, Dark Amul Chocolate Brownie and Cashew Brownie. Final price varies by flavour and quantity — contact us for a personalised quote.",
    price: 899,
    unit: "per kg (starting from)",
    image: PX("19846422", ""),
    tags: "Eggless,7 Flavours,Bulk Friendly",
    rating: 4.9,
    reviews: 88,
    sortOrder: 9,
  },
  {
    name: "Healthy Millet Protein Cake",
    slug: "healthy-millet-protein-cake",
    category: "healthy",
    shortDesc: "No maida. No sugar. Ragi, jowar, whole wheat + premium nuts.",
    description:
      "Made with the goodness of ragi, jowar, whole wheat and other nutritious millets, blended with fresh eggs, premium nuts and carefully selected ingredients for a naturally soft, moist and protein-rich cake. Each cake is served with our signature homemade chocolate sauce. No maida, no sugar.",
    price: 999,
    unit: "per kg",
    image: "/images/millet-protein-cake.jpg",
    tags: "No Maida,No Sugar,High Protein,Contains Egg",
    isEggless: false,
    rating: 4.8,
    reviews: 64,
    sortOrder: 10,
  },
  {
    name: "Signature Plum Cake",
    slug: "signature-plum-cake",
    category: "healthy",
    shortDesc: "Soft, rich and full of flavour with premium dry fruits.",
    description:
      "Freshly baked with fresh eggs, whole wheat flour, refined flour and premium dry fruits for a perfectly moist and delicious treat. Our festive signature.",
    price: 999,
    unit: "per kg",
   image: "/images/plum-cake.jpg",
    tags: "Festive,Dry Fruits,Contains Egg",
    isEggless: false,
    rating: 4.9,
    reviews: 52,
    sortOrder: 11,
  },
  {
    name: "Customized Cakes",
    slug: "customized-cakes",
    category: "custom",
    shortDesc: "Designed to match your celebration, style and vision.",
    description:
      "Every cake is uniquely designed to match your celebration, style and vision. From elegant birthdays and anniversaries to weddings, baby showers and special occasions, each cake is handcrafted with premium ingredients and exceptional attention to detail. Because every order is personalised, pricing varies based on cake size, flavour, design and level of customisation.",
    price: 0,
    priceOnRequest: true,
    unit: "price on request",
    image: "/images/custom-cake.jpg",
    tags: "Made To Order,Any Theme,3 Days Notice",
    isBestseller: true,
    rating: 5,
    reviews: 96,
    sortOrder: 12,
  },
];
